---
namespace: fmjstudios
name: deployments
version: 0.0.1
readme: README.md
authors:
  - Maximilian Gindorfer <info@fmj.dev>
description: delta4x4 Ansible collection for deployments
license_file: "LICENSE"
tags:
  - deployment
  - ci-cd
  - devops
dependencies: {}
repository: http://example.com/repository
documentation: http://docs.example.com
homepage: http://fmj.dev
issues: http://example.com/issue/tracker
build_ignore:
  - .gitignore
  - LICENSE
  - Makefile
  - AUTHORS
  - .vscode
  - .github